<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <RootNamespace>DellFanManagement.Service</RootNamespace>
    <AssemblyName>DellFanService</AssemblyName>
    <PlatformTarget>x64</PlatformTarget>
    <Version>1.0.0</Version>
    <Authors>Dell Fan Management contributors</Authors>
    <Product>Dell Fan Service</Product>
    <Copyright>GPLv3</Copyright>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <!-- 单文件发布配置 -->
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishTrimmed>false</PublishTrimmed>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="6.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="6.0.0" />
    <PackageReference Include="System.Management" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DellSmbiosBzhLib\DellSmbiosBzhLib.csproj" />
    <ProjectReference Include="..\DellSmbiosSmiLib\DellSmbiosSmiLib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="bzh_dell_smm_io_x64.sys">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
