<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <RootNamespace>ECFanLevelProbe</RootNamespace>
    <AssemblyName>ECFanLevelProbe</AssemblyName>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DellSmbiosBzhLib\DellSmbiosBzhLib.csproj" />
  </ItemGroup>

</Project>
